import LocalizedStrings from 'react-localization'

let strings = new LocalizedStrings({
    en:{
        signIn: "Sign In",
        signUp: "Sign Up",
        emailAddress: "Email Address",
        username: "Username",
        password: "Password",
        confirmPassword: "Confirm Password",
        rememberMe: "Remember Me",
        forgotPass: "Forgot Password?",
        noAccount: "Don't have an account? Sign Up",
        welcome: "Welcome to the progressive web application that provides information about current status of three most popular areas in Nokia HQ, Espoo",
        logoAlt: "MyCampus Logo",
        validEmail: "Please enter a valid email",
        enterEmail: "Enter the email you want the password to be reset and click send",
        send: "Send",
        joinPlatform: "Join Nokia MyCampus platform",
        backToLogin: "Back to Login",
        usernameError: "Username must be between 2-20 characters",
        passwordError: "Passwords don't match",
        pleaseEnterEmail: "Please enter an email",
        pleaseEnterConfirmPass: "Please enter password confirmation",
        pleaseEnterPassword: "Please enter an password",
        pleaseEnterName: "Please enter a name",
        waitTime1: "wait time < 30s",
        waitTime2: "wait time < 1m",
        waitTime3: "wait time < 1m 30s",
        waitTime4: "wait time < 2m",
        waitTime5: "wait time > 2m",
        restaurantPageTitle: "Queue Times",
        p10PageTitle: "P10",
        live: "Live",
        history: "History",
        pleaseEnterUsername: "Please enter an username",
        topBarMenuItemHome: "Home",
        topBarMenuItemRestaurant: "Restaurant",
        topBarMenuItemP5: "P5",
        topBarMenuItemP10: "P10",
        topBarMenuItemInfo: "Info",
        topBarMenuItemLogout: "Logout"
    },
    fi:{
        signIn: "Kirjaudu",
        signUp: "Rekisteröidy",
        emailAddress: "Sähköposti",
        username: "Käyttäjänimi",
        password: "Salasana",
        confirmPassword: "Varmista salasana",
        rememberMe: "Muista minut",
        forgotPass: "Unohtuiko salasana?",
        noAccount: "Ei käyttäjätiliä? Rekisteröidy",
        welcome: "Tervetuloa progressiiviseen verkko sovellukseen joka tarjoaa tietoa Nokian Karamalmin kampuksen kolmesta suosituimmasta paikasta.",
        logoAlt: "MyCampus Logo",
        validEmail: "Syötä sähköposti",
        enterEmail: "Syötä sähköposti jonka salasanan tahdot resetoida ja paina lähetä",
        send: "Lähetä",
        joinPlatform: "Liity Nokia MyCampus alustalle",
        usernameError: "Käyttäjänimen tulee olla 2-20 merkkiä pitkä",
        passwordError: "Salasanat eivät täsmää",
        pleaseEnterEmail: "Syötä sähköposti",
        pleaseEnterConfirmPass: "Syötä salasanan vahvistus",
        pleaseEnterPassword: "Syötä salasana",
        pleaseEnterUsername: "Syötä käyttäjänimi",
        pleaseEnterName: "Syötä nimi",
        waitTime1: "jonotusaika < 30s",
        waitTime2: "jonotusaika < 1m",
        waitTime3: "jonotusaika < 1m 30s",
        waitTime4: "jonotusaika < 2m",
        waitTime5: "jonotusaika > 2m",
        restaurantPageTitle: "Jonotusajat",
        p10PageTitle: "P10",
        live: "Live",
        history: "Vanha Data",
        topBarMenuItemHome: "Home",
        topBarMenuItemRestaurant: "Restaurant",
        topBarMenuItemP5: "P5",
        topBarMenuItemP10: "P10",
        topBarMenuItemLogout: "Kirjaudu Ulos"
    }
});

export default strings;
